apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  annotations:
    sidecar.jaegertracing.io/inject: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      release: prometheus
  template:
    metadata:
      labels:
        app: backend
        release: prometheus
    spec:
      containers:
      - name: backend
        image: amh23/backend:latest
        ports:
        - containerPort: 8081
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
